spring:
  security:
    filter:
      order: 10
  datasource:
    url: jdbc:postgresql://localhost:5432/telegram
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        ddl-auto: validate
        default_schema: public
  liquibase:
    change-log: db/migration/liquibase-changelog.xml
    enabled: true
    drop-first: false
    default-schema: public

security:
  secret-key: 0e4b2d66-9b81-4797-b053-6e8483cee082

bot:
  name: spring_tg_bot
  apikey: 5556567984:AAG2wAHI074u8qxi-1GBhCbejV8bCFpzU8I